## Import libraries and packages

In [ ]:
# import packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Import Datasets

In [ ]:
# mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 1. Amazon Product Reviews Dataset

This is a scraped dataset from Sep 2023 from Amazon, contains more than 1.4M  pricing & sales data from the customer in USA. There are two related datasets: i) amazon_categories.csv
ii) amazon_products.csv

In [ ]:
# read csv and view first 10 rows
df_categories = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/amazon_categories.csv')
df_amz_products= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/amazon_products.csv')

df_categories.head(10)

   id                     category_name
0   1          Beading & Jewelry Making
1   2                 Fabric Decorating
2   3       Knitting & Crochet Supplies
3   4              Printmaking Supplies
4   5  Scrapbooking & Stamping Supplies
5   6                   Sewing Products
6   7              Craft & Hobby Fabric
7   8               Needlework Supplies
8   9     Arts, Crafts & Sewing Storage
9  10  Painting, Drawing & Art Supplies

In [ ]:
df_amz_products.head(10)

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400
5,B07XSCD2R4,Maxlite 5 Softside Expandable Luggage with 4 S...,https://m.media-amazon.com/images/I/61LnBNsSBS...,https://www.amazon.com/dp/B07XSCD2R4,4.5,0,144.49,0.00,104,False,500
6,B07MXF4G8K,"Hard Shell Carry on Luggage Airline Approved, ...",https://m.media-amazon.com/images/I/71CghLYrnA...,https://www.amazon.com/dp/B07MXF4G8K,4.5,0,169.99,0.00,104,False,400
7,B07H515VCZ,"Maxporter II 30"" Hardside Spinner Trunk Luggag...",https://m.media-amazon.com/images/I/81f3h+YHOX...,https://www.amazon.com/dp/B07H515VCZ,4.5,0,299.99,0.00,104,False,100
8,B08BXBCNMQ,Omni 2 Hardside Expandable Luggage with Spinne...,https://m.media-amazon.com/images/I/91eOWP4myS...,https://www.amazon.com/dp/B08BXBCNMQ,4.5,0,112.63,137.04,104,False,500
9,B0B9K44XTS,Luggage Sets Expandable Lightweight Suitcases ...,https://m.media-amazon.com/images/I/81dsv5GrCL...,https://www.amazon.com/dp/B0B9K44XTS,4.4,0,209.99,0.00,104,False,200

In [ ]:
df_categories.info()
df_amz_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             248 non-null    int64
 1   category_name  248 non-null    object
dtypes: int64(1), object(1)
memory usage: 4.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426337 entries, 0 to 1426336
Data columns (total 11 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   asin               1426337 non-null  object
 1   title              1426336 non-null  object
 2   imgUrl             1426337 non-null  object
 3   productURL         1426337 non-null  object
 4   stars              1426337 non-null  float64
 5   reviews            1426337 non-null  int64
 6   price              1426337 non-null  float64
 7   listPrice          1426337 non-null  float64
 8   category_id        1426337 non-null  int64
 9   isBestSeller       1426337 non-null  bool
 10  boughtInLastMonth  1426337 non-null  int64
dtypes: bool(1), float64(3), int64(3), object(4)
memory usage: 110.2+ MB

#### Data cleaning

In [ ]:
df_categories.isna().sum()

id               0
category_name    0
dtype: int64

In [ ]:
df_amz_products.isna().sum()

asin                 0
title                1
imgUrl               0
productURL           0
stars                0
reviews              0
price                0
listPrice            0
category_id          0
isBestSeller         0
boughtInLastMonth    0
dtype: int64

In [ ]:
df_amz_products=df_amz_products.dropna()
df_amz_products.isna().sum() == 0

asin                 True
title                True
imgUrl               True
productURL           True
stars                True
reviews              True
price                True
listPrice            True
category_id          True
isBestSeller         True
boughtInLastMonth    True
dtype: bool

In [ ]:
df_amz_products.duplicated().sum()

np.int64(0)

In [ ]:
# merge two csv file with the category id match to id
product_review = df_amz_products.merge(df_categories, left_on='category_id', right_on='id', how='left')
product_review = product_review.drop(columns=['id', 'category_id'])
product_review.head(10)

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,isBestSeller,boughtInLastMonth,category_name
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,False,2000,Suitcases
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,False,1000,Suitcases
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,False,300,Suitcases
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,False,400,Suitcases
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,False,400,Suitcases
5,B07XSCD2R4,Maxlite 5 Softside Expandable Luggage with 4 S...,https://m.media-amazon.com/images/I/61LnBNsSBS...,https://www.amazon.com/dp/B07XSCD2R4,4.5,0,144.49,0.00,False,500,Suitcases
6,B07MXF4G8K,"Hard Shell Carry on Luggage Airline Approved, ...",https://m.media-amazon.com/images/I/71CghLYrnA...,https://www.amazon.com/dp/B07MXF4G8K,4.5,0,169.99,0.00,False,400,Suitcases
7,B07H515VCZ,"Maxporter II 30"" Hardside Spinner Trunk Luggag...",https://m.media-amazon.com/images/I/81f3h+YHOX...,https://www.amazon.com/dp/B07H515VCZ,4.5,0,299.99,0.00,False,100,Suitcases
8,B08BXBCNMQ,Omni 2 Hardside Expandable Luggage with Spinne...,https://m.media-amazon.com/images/I/91eOWP4myS...,https://www.amazon.com/dp/B08BXBCNMQ,4.5,0,112.63,137.04,False,500,Suitcases
9,B0B9K44XTS,Luggage Sets Expandable Lightweight Suitcases ...,https://m.media-amazon.com/images/I/81dsv5GrCL...,https://www.amazon.com/dp/B0B9K44XTS,4.4,0,209.99,0.00,False,200,Suitcases

In [ ]:
# drop imgUrl and productURL
product_review = product_review.drop(columns=['imgUrl', 'productURL'])
product_review.head(10)

,asin,title,stars,reviews,price,listPrice,isBestSeller,boughtInLastMonth,category_name
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",4.5,0,139.99,0.00,False,2000,Suitcases
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,4.5,0,169.99,209.99,False,1000,Suitcases
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,4.6,0,365.49,429.99,False,300,Suitcases
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,4.6,0,291.59,354.37,False,400,Suitcases
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,4.5,0,174.99,309.99,False,400,Suitcases
5,B07XSCD2R4,Maxlite 5 Softside Expandable Luggage with 4 S...,4.5,0,144.49,0.00,False,500,Suitcases
6,B07MXF4G8K,"Hard Shell Carry on Luggage Airline Approved, ...",4.5,0,169.99,0.00,False,400,Suitcases
7,B07H515VCZ,"Maxporter II 30"" Hardside Spinner Trunk Luggag...",4.5,0,299.99,0.00,False,100,Suitcases
8,B08BXBCNMQ,Omni 2 Hardside Expandable Luggage with Spinne...,4.5,0,112.63,137.04,False,500,Suitcases
9,B0B9K44XTS,Luggage Sets Expandable Lightweight Suitcases ...,4.4,0,209.99,0.00,False,200,Suitcases

In [ ]:
# Save to CSV
product_review.to_csv('clean_product_review.csv', index=False)

In [ ]:
# Split the product review into 2 file
half = len(product_review) // 2
product_review1 = product_review.iloc[:half]
product_review2 = product_review.iloc[half:]

### 2. Amazon Logistic Partner Dataset

This dataset contains >1000 Amazon warehouse location prepared by AMZ Prep, a Amazon FBA (Fulfilment by Amazon) logistic partner. The data is stored in one excel file with 3 different sheets, indicating warehouse location in USA, Canada and the inventory management tool used by different FBA partners.

This dataset can be used for:
- Planning inbound shipments
- Mapping transit lanes
- Optimizing carrier selection
- Tracking fulfillment performance

In [ ]:
# read excelfile and seperate the sheets into 3 different dataframe
fbalocation = pd.ExcelFile('/content/drive/MyDrive/Colab Notebooks/Dataset/Amazon FBA Locations 2025 (UPDATED) - Master List [AMZ Prep].xlsx')

df_usa = pd.read_excel(fbalocation, sheet_name=0, header=2)
df_canada = pd.read_excel(fbalocation, sheet_name=1, header=2)
df_inventory_tool = pd.read_excel(fbalocation, sheet_name=2, header=1)

In [ ]:
df_usa.info()
df_canada.info()
df_inventory_tool.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1047 entries, 0 to 1046
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Location  1045 non-null   object
 1   Code      1043 non-null   object
 2   Type      633 non-null    object
 3   Address   1043 non-null   object
dtypes: object(4)
memory usage: 32.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   State    25 non-null     object
 1   Code     25 non-null     object
 2   Type     19 non-null     object
 3   Address  24 non-null     object
dtypes: object(4)
memory usage: 932.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      119 non-null    object
 1   Domain       119 non-null    object
 2   Description  119 non-null    object
dtypes: object(3)
memory usage: 2.9+ KB

In [ ]:
df_usa.head(10)

,Location,Code,Type,Address
0,Alabama,BHM1,FC,"975 Powder Plant Rd, Bessemer, AL 35022, Unite..."
1,Alabama,DPX7,NaN,"3405 S. McQueen Rd, Chandler, AZ"
2,Alabama,MOB5,DC,"6735 Trippel Rd, Theodore, AL 36582, United St..."
3,Alabama,MOB9,NaN,"6735 Trippel Rd., Theodore, AL"
4,Alabama,SUHB,NaN,"4675 Appaloosa Dr, Irondale, AL"
5,Alabama,SUHD,NaN,"4675 Appaloosa Drive, Irondale, AL"
6,Arizona,SAZ1,FC,"3333 S 7th St., Phoenix, AZ 850401182 , Marico..."
7,Arizona,TUS1,Reverse Logistics,"533 W Lower Buckeye Rd, Phoenix, Arizona, 8504..."
8,Arizona,TUS2,FC,"6701 S. Kolb Rd., Tucson, AZ 85756 , Pima County"
9,Arizona,AZA4,NaN,"3333 S 59th Ave, Phoenix, Arizona"

In [ ]:
df_canada.head(10)

,State,Code,Type,Address
0,Alberta,XCAB,NaN,"1882 118 Avenue NE, Calgary, AB"
1,Alberta,YYC1,FC,"293069 Col Robertson Way, Rocky View County, A..."
2,British Columbia,DVC1,DC,"4242 Phillips Ave, Burnaby, BC V5A 2X2, Canada"
3,British Columbia,UBC1,NaN,"8155 N Fraser Way, Burnaby, BC"
4,British Columbia,YVR1,FC,"450 Derwent PL Delta, British Columbia V3M 5Y9"
5,British Columbia,YVR2,FC,"450 Derwent PL Delta, British Columbia V3M 5Y9"
6,British Columbia,YVR3,FC,"109 Braid St, New Westminster, BC V3L 3R9, Canada"
7,British Columbia,YVR4,FC,"4189 Salish Sea Way, Tsawwassen (Delta), Briti..."
8,Edmonton,YEG1,FC,"1440 39 Ave, Nisku, Leduc County, AB T6W 1A7"
9,Ontario,YYZ10,FC,NaN

In [ ]:
df_inventory_tool.head(10)

,Company,Domain,Description
0,AMZ Prep,amzprep.com,FBA Prep & eCommerce Fulfillment across Canada...
1,Acctivate,acctivate.com,Amazon FBA Inventory Management Software
2,Jazva,jazva.com,Amazon Inventory & Order Processing Tools
3,SolidCommerce,solidcommerce.com,Amazon Inventory and Order Management
4,Orderhive,orderhive.com,Amazon Inventory and Order Management
5,Finale Inventory,finaleinventory.com,Amazon Inventory Management tools
6,SkuVault,skuvault.com,Amazon Inventory Management tools
7,Amlister,amlister.com,Amazon Inventory on eBay Lister
8,RepriceIt,repriceit.com,Amazon Inventory Repricing
9,Multiply Mii,multiplymii.com,Amazon Outsourcing Software

#### Data cleaning

1. Checking null for df_usa, which contain USA warehouse location

In [ ]:
df_usa.isna().sum()

Location      2
Code          4
Type        414
Address       4
dtype: int64

Dropping type column due to large value of missing data. Other rows with null value are drop as they are less than 5% of total rows

In [ ]:
# dropping type column
df_usa= df_usa.drop(columns= ['Type'])

# drop other row containing null value
df_usa=df_usa.dropna()
df_usa.isna().sum() == 0

Location    True
Code        True
Address     True
dtype: bool

2. Checking null for df_canada, which contain Canada warehouse location

In [ ]:
df_canada.isna().sum()

State      0
Code       0
Type       6
Address    1
dtype: int64

Dropping type column for the same reason as usa location

In [ ]:
# dropping type column
df_canada= df_canada.drop(columns= ['Type'])

# drop other row containing null value
df_canada=df_canada.dropna()
df_canada.isna().sum() == 0

State      True
Code       True
Address    True
dtype: bool

In [ ]:
df_inventory_tool.isna().sum()

Company        0
Domain         0
Description    0
dtype: int64

In [ ]:
print(df_usa.duplicated().sum())
print(df_canada.duplicated().sum())
print(df_inventory_tool.duplicated().sum())

2
0
1

In [ ]:
# dropping duplicated values
df_usa.drop_duplicates(inplace=True)
df_inventory_tool.drop_duplicates(inplace=True)

### 3. Amazon Stocks Dataset
This dataset provides historical stock market data for Amazon (AMZN) from  1977 to 2025. The data has been sourced from Yahoo Finance and includes essential stock market attributes for analysis market trends, volatility, and stock performance.

In [ ]:
# read csv and view first 10 rows
df_stocks = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/AMZN_stock_data.csv')
df_stocks.head(10)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1997-05-15 00:00:00-04:00,0.121875,0.125000,0.096354,0.097917,1443120000,0.0,0.0
1,1997-05-16 00:00:00-04:00,0.098438,0.098958,0.085417,0.086458,294000000,0.0,0.0
2,1997-05-19 00:00:00-04:00,0.088021,0.088542,0.081250,0.085417,122136000,0.0,0.0
3,1997-05-20 00:00:00-04:00,0.086458,0.087500,0.081771,0.081771,109344000,0.0,0.0
4,1997-05-21 00:00:00-04:00,0.081771,0.082292,0.068750,0.071354,377064000,0.0,0.0
5,1997-05-22 00:00:00-04:00,0.071875,0.072396,0.065625,0.069792,235536000,0.0,0.0
6,1997-05-23 00:00:00-04:00,0.070313,0.076042,0.066667,0.075000,318744000,0.0,0.0
7,1997-05-27 00:00:00-04:00,0.075521,0.082292,0.072917,0.079167,173952000,0.0,0.0
8,1997-05-28 00:00:00-04:00,0.081250,0.081771,0.076563,0.076563,91488000,0.0,0.0
9,1997-05-29 00:00:00-04:00,0.077083,0.077083,0.073958,0.075260,69456000,0.0,0.0

In [ ]:
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6987 entries, 0 to 6986
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          6987 non-null   object
 1   Open          6987 non-null   float64
 2   High          6987 non-null   float64
 3   Low           6987 non-null   float64
 4   Close         6987 non-null   float64
 5   Volume        6987 non-null   int64
 6   Dividends     6987 non-null   float64
 7   Stock Splits  6987 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 436.8+ KB

#### Data cleaning

In [ ]:
df_stocks.isna().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [ ]:
df_stocks.duplicated().sum()

np.int64(0)

The dataset is clean with no null value and duplicated value found.

In [ ]:
# convert Date column to datetime
df_stocks['Date'] = pd.to_datetime(df_stocks['Date'], utc=True)
df_stocks.info()
df_stocks.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6987 entries, 0 to 6986
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          6987 non-null   datetime64[ns, UTC]
 1   Open          6987 non-null   float64
 2   High          6987 non-null   float64
 3   Low           6987 non-null   float64
 4   Close         6987 non-null   float64
 5   Volume        6987 non-null   int64
 6   Dividends     6987 non-null   float64
 7   Stock Splits  6987 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(6), int64(1)
memory usage: 436.8 KB

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1997-05-15 04:00:00+00:00,0.121875,0.125000,0.096354,0.097917,1443120000,0.0,0.0
1,1997-05-16 04:00:00+00:00,0.098438,0.098958,0.085417,0.086458,294000000,0.0,0.0
2,1997-05-19 04:00:00+00:00,0.088021,0.088542,0.081250,0.085417,122136000,0.0,0.0
3,1997-05-20 04:00:00+00:00,0.086458,0.087500,0.081771,0.081771,109344000,0.0,0.0
4,1997-05-21 04:00:00+00:00,0.081771,0.082292,0.068750,0.071354,377064000,0.0,0.0

In [ ]:
# due to excel not supporting timezone, make the column timezone unaware before integration
df_stocks['Date'] = df_stocks['Date'].dt.tz_localize(None)

df_stocks.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1997-05-15 04:00:00,0.121875,0.125000,0.096354,0.097917,1443120000,0.0,0.0
1,1997-05-16 04:00:00,0.098438,0.098958,0.085417,0.086458,294000000,0.0,0.0
2,1997-05-19 04:00:00,0.088021,0.088542,0.081250,0.085417,122136000,0.0,0.0
3,1997-05-20 04:00:00,0.086458,0.087500,0.081771,0.081771,109344000,0.0,0.0
4,1997-05-21 04:00:00,0.081771,0.082292,0.068750,0.071354,377064000,0.0,0.0

### 4. Amazon Financial Dataset
This section contains 4 datasets scraped from Yahoo! Finance’s API from 2021 to 2025. This include Amazon yearly income statement, Amazon quarterly income statement, Amazon balance sheet, and Amazon cash flow data.

In [ ]:
# read all 4 csv
df_income_stmt = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/amznincome_stmt.csv')
df_quarter_income = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/amznquarterly_incomestmt.csv')
df_balance_sheet = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/amznbalance_sheet.csv')
df_cash_flow = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/amzncash_flow.csv')

In [ ]:
# view the first 5 rows
df_income_stmt.head(5)

,Unnamed: 0,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
0,Tax Effect Of Unusual Items,-2.469712e+08,2.113800e+08,-3.415860e+09,1.839997e+09,NaN
1,Tax Rate For Calcs,1.350310e-01,1.895790e-01,2.100000e-01,1.255800e-01,NaN
2,Normalized EBITDA,1.256440e+11,8.828700e+10,5.461800e+10,5.974100e+10,NaN
3,Total Unusual Items,-1.829000e+09,1.115000e+09,-1.626600e+10,1.465200e+10,NaN
4,Total Unusual Items Excluding Goodwill,-1.829000e+09,1.115000e+09,-1.626600e+10,1.465200e+10,NaN

In [ ]:
df_quarter_income.head(5)

,Unnamed: 0,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31
0,Tax Effect Of Unusual Items,5.842726e+08,5.971408e+07,-2.700449e+06,4.636274e+06,-4.609830e+08
1,Tax Rate For Calcs,2.100190e-01,1.040320e-01,1.500250e-01,1.159070e-01,1.900180e-01
2,Normalized EBITDA,3.370000e+10,3.797600e+10,3.210000e+10,2.783200e+10,2.773700e+10
3,Total Unusual Items,2.782000e+09,5.740000e+08,-1.800000e+07,4.000000e+07,-2.426000e+09
4,Total Unusual Items Excluding Goodwill,2.782000e+09,5.740000e+08,-1.800000e+07,4.000000e+07,-2.426000e+09

In [ ]:
df_balance_sheet.head(5)

,Unnamed: 0,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
0,Treasury Shares Number,5.150000e+08,5.150000e+08,5.150000e+08,4.600000e+08,NaN
1,Ordinary Shares Number,1.059300e+10,1.038300e+10,1.024200e+10,1.018000e+10,NaN
2,Share Issued,1.110800e+10,1.089800e+10,1.075700e+10,1.064000e+10,NaN
3,Net Debt,NaN,NaN,1.326200e+10,1.252400e+10,NaN
4,Total Debt,1.309000e+11,1.356110e+11,1.401180e+11,1.163950e+11,NaN

In [ ]:
df_cash_flow.head(5)

,Unnamed: 0,2024-12-31,2023-12-31,2022-12-31,2021-12-31
0,Free Cash Flow,3.287800e+10,3.221700e+10,-1.689300e+10,-1.472600e+10
1,Repurchase Of Capital Stock,0.000000e+00,0.000000e+00,-6.000000e+09,0.000000e+00
2,Repayment Of Debt,-1.695400e+10,-3.400800e+10,-4.700100e+10,-2.066800e+10
3,Issuance Of Debt,5.142000e+09,1.812900e+10,6.271900e+10,2.695900e+10
4,Capital Expenditure,-8.299900e+10,-5.272900e+10,-6.364500e+10,-6.105300e+10

In [ ]:
df_income_stmt.info()
df_quarter_income.info()
df_balance_sheet.info()
df_cash_flow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  47 non-null     object
 1   2024-12-31  46 non-null     float64
 2   2023-12-31  46 non-null     float64
 3   2022-12-31  46 non-null     float64
 4   2021-12-31  46 non-null     float64
 5   2020-12-31  1 non-null      float64
dtypes: float64(5), object(1)
memory usage: 2.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  46 non-null     object
 1   2025-03-31  46 non-null     float64
 2   2024-12-31  46 non-null     float64
 3   2024-09-30  46 non-null     float64
 4   2024-06-30  46 non-null     float64
 5   2024-03-31  46 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  61 non-null     object
 1   2024-12-31  57 non-null     float64
 2   2023-12-31  58 non-null     float64
 3   2022-12-31  59 non-null     float64
 4   2021-12-31  61 non-null     float64
 5   2020-12-31  3 non-null      float64
dtypes: float64(5), object(1)
memory usage: 3.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  52 non-null     object
 1   2024-12-31  51 non-null     float64
 2   2023-12-31  52 non-null     float64
 3   2022-12-31  52 non-null     float64
 4   2021-12-31  52 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.2+ KB

From the info, it can be seen that for df_income_stmt, year 2020 only contains one value and df_balance_sheet column 2020 contains only 3 values.These columns will be removed in next step.

#### Data cleaning

The 4 datasets is cleaned in order by checking nulls and dropping missing values. Then, duplicated values are checked.

1. Income statement

In [ ]:
# check null for income statement dataset
df_income_stmt.isna().sum()

Unnamed: 0     0
2024-12-31     1
2023-12-31     1
2022-12-31     1
2021-12-31     1
2020-12-31    46
dtype: int64

In [ ]:
# dropping column 2020-12-31
df_income_stmt=df_income_stmt.drop(columns=['2020-12-31'])

2. Quarterly income statement

In [ ]:
# check null for quarter income statement dataset
df_quarter_income.isna().sum()

Unnamed: 0    0
2025-03-31    0
2024-12-31    0
2024-09-30    0
2024-06-30    0
2024-03-31    0
dtype: int64

3. Balance sheet

In [ ]:
# check null for balance sheet
df_balance_sheet.isna().sum()

Unnamed: 0     0
2024-12-31     4
2023-12-31     3
2022-12-31     2
2021-12-31     0
2020-12-31    58
dtype: int64

In [ ]:
# dropping column 2020-12-31
df_balance_sheet=df_balance_sheet.drop(columns=['2020-12-31'])

4. Cash flow

In [ ]:
# check null for cash flow
df_cash_flow.isna().sum()

Unnamed: 0    0
2024-12-31    1
2023-12-31    0
2022-12-31    0
2021-12-31    0
dtype: int64

The other null value aside from 2020 column are not removed. This is because financial statement are interconnected, and removing the rows with missing values might affects the balance of the accounting sheets and break ratio and trends.

In [ ]:
print(df_income_stmt.duplicated().sum())
print(df_quarter_income.duplicated().sum())
print(df_balance_sheet.duplicated().sum())
print(df_cash_flow.duplicated().sum())

0
0
0
0

In [ ]:
# transposing the dataset so the year are listed in one column and each observations (revenue, net debt etc) is across the columns

transp_income_stmt = df_income_stmt.transpose()
transp_quarter_income = df_quarter_income.transpose()
transp_balance_sheet = df_balance_sheet.transpose()
transp_cash_flow = df_cash_flow.transpose()

In [ ]:
# checking the data
df_income_stmt.head(5)

,Unnamed: 0,2024-12-31,2023-12-31,2022-12-31,2021-12-31
0,Tax Effect Of Unusual Items,-2.469712e+08,2.113800e+08,-3.415860e+09,1.839997e+09
1,Tax Rate For Calcs,1.350310e-01,1.895790e-01,2.100000e-01,1.255800e-01
2,Normalized EBITDA,1.256440e+11,8.828700e+10,5.461800e+10,5.974100e+10
3,Total Unusual Items,-1.829000e+09,1.115000e+09,-1.626600e+10,1.465200e+10
4,Total Unusual Items Excluding Goodwill,-1.829000e+09,1.115000e+09,-1.626600e+10,1.465200e+10

In [ ]:
# define a function to promote first row as header and reset the index
def promote_header(df, index_name='Year'):
    df.columns = df.iloc[0]                     # Promote first row to column headers
    df = df.drop(df.index[0])                   # Drop that row from data
    df.index.name = index_name                  # Rename index
    return df.reset_index()


# apply function all of the data
transp_income_stmt = promote_header(transp_income_stmt)
transp_quarter_income = promote_header(transp_quarter_income)
transp_balance_sheet = promote_header(transp_balance_sheet)
transp_cash_flow = promote_header(transp_cash_flow)

In [ ]:
# Correct the data type
# convert year column to datetime

transp_income_stmt['Year'] = pd.to_datetime(transp_income_stmt['Year'])
transp_quarter_income['Year'] = pd.to_datetime(transp_quarter_income['Year'])
transp_balance_sheet['Year'] = pd.to_datetime(transp_balance_sheet['Year'])
transp_cash_flow['Year'] = pd.to_datetime(transp_cash_flow['Year'])

In [ ]:
# checking the data
print(transp_income_stmt.head(5))
print(transp_income_stmt.info())

Unnamed: 0       Year Tax Effect Of Unusual Items Tax Rate For Calcs  \
0          2024-12-31           -246971244.935436           0.135031
1          2023-12-31            211380035.679101           0.189579
2          2022-12-31               -3415860000.0               0.21
3          2021-12-31           1839997169.143666            0.12558

Unnamed: 0 Normalized EBITDA Total Unusual Items  \
0             125644000000.0       -1829000000.0
1              88287000000.0        1115000000.0
2              54618000000.0      -16266000000.0
3              59741000000.0       14652000000.0

Unnamed: 0 Total Unusual Items Excluding Goodwill  \
0                                   -1829000000.0
1                                    1115000000.0
2                                  -16266000000.0
3                                   14652000000.0

Unnamed: 0 Net Income From Continuing Operation Net Minority Interest  \
0                                               59248000000.0
1                                               30425000000.0
2                                               -2722000000.0
3                                               33364000000.0

Unnamed: 0 Reconciled Depreciation Reconciled Cost Of Revenue          EBITDA  \
0                    52795000000.0             326288000000.0  123815000000.0
1                    48663000000.0             304739000000.0   89402000000.0
2                    41921000000.0             288831000000.0   38352000000.0
3                    34433000000.0             272344000000.0   74393000000.0

Unnamed: 0  ... Other Operating Expenses Research And Development  \
0           ...           187812000000.0                      NaN
1           ...           177008000000.0                      NaN
2           ...           158775000000.0                      NaN
3           ...           131225000000.0                      NaN

Unnamed: 0 Selling General And Administration Selling And Marketing Expense  \
0                               55266000000.0                 43907000000.0
1                               56186000000.0                 44370000000.0
2                               54129000000.0                 42238000000.0
3                               41374000000.0                 32551000000.0

Unnamed: 0 General And Administrative Expense   Other Gand A    Gross Profit  \
0                               11359000000.0  11359000000.0  311671000000.0
1                               11816000000.0  11816000000.0  270046000000.0
2                               11891000000.0  11891000000.0  225152000000.0
3                                8823000000.0   8823000000.0  197478000000.0

Unnamed: 0 Cost Of Revenue   Total Revenue Operating Revenue
0           326288000000.0  637959000000.0    637959000000.0
1           304739000000.0  574785000000.0    574785000000.0
2           288831000000.0  513983000000.0    513983000000.0
3           272344000000.0  469822000000.0    469822000000.0

[4 rows x 48 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 48 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Year                                                        4 non-null      datetime64[ns]
 1   Tax Effect Of Unusual Items                                 4 non-null      object
 2   Tax Rate For Calcs                                          4 non-null      object
 3   Normalized EBITDA                                           4 non-null      object
 4   Total Unusual Items                                         4 non-null      object
 5   Total Unusual Items Excluding Goodwill                      4 non-null      object
 6   Net Income From Continuing Operation Net Minority Interest  4 non-null      object
 7   Reconciled Depreciation                                     4 non-null      object
 8   Reconciled Cost Of Revenue                                  4 non-null      object
 9   EBITDA                                                      4 non-null      object
 10  EBIT                                                        4 non-null      object
 11  Net Interest Income                                         4 non-null      object
 12  Interest Expense                                            4 non-null      object
 13  Interest Income                                             4 non-null      object
 14  Normalized Income                                           4 non-null      object
 15  Net Income From Continuing And Discontinued Operation       4 non-null      object
 16  Total Expenses                                              4 non-null      object
 17  Total Operating Income As Reported                          4 non-null      object
 18  Diluted Average Shares                                      4 non-null      object
 19  Basic Average Shares                                        4 non-null      object
 20  Diluted EPS                                                 4 non-null      object
 21  Basic EPS                                                   4 non-null      object
 22  Diluted NI Availto Com Stockholders                         4 non-null      object
 23  Net Income Common Stockholders                              4 non-null      object
 24  Net Income                                                  4 non-null      object
 25  Net Income Including Noncontrolling Interests               4 non-null      object
 26  Net Income Continuous Operations                            4 non-null      object
 27  Earnings From Equity Interest Net Of Tax                    4 non-null      object
 28  Tax Provision                                               4 non-null      object
 29  Pretax Income                                               4 non-null      object
 30  Other Income Expense                                        4 non-null      object
 31  Other Non Operating Income Expenses                         4 non-null      object
 32  Gain On Sale Of Security                                    4 non-null      object
 33  Net Non Operating Interest Income Expense                   4 non-null      object
 34  Interest Expense Non Operating                              4 non-null      object
 35  Interest Income Non Operating                               4 non-null      object
 36  Operating Income                                            4 non-null      object
 37  Operating Expense                                           4 non-null      object
 38  Other Operating Expenses                                    4 non-null      object
 39  Research And Development                                    0 non-null      object
 40  Selling General And Administration                          4 non-null      object
 41  Selling And Marketing Expense                               4 non-null      object
 42  General And Administrative Expense                          4 non-null      object
 43  Other Gand A                                                4 non-null      object
 44  Gross Profit                                                4 non-null      object
 45  Cost Of Revenue                                             4 non-null      object
 46  Total Revenue                                               4 non-null      object
 47  Operating Revenue                                           4 non-null      object
dtypes: datetime64[ns](1), object(47)
memory usage: 1.6+ KB
None

### 5. Amazon Market Competitor Dataset

This datasets provides a comprehensive overview of Walmart and Costco in the United States,which are the direct competitors of Amazon covering the period from 2015 to 2025. There are 3 individual datasets which will be merged into one. These dataset contains revenue, market share and market spend data for the competitors.

In [ ]:
# read all 3 csv
df_costco= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/Costco_US_Revenue_and_Marketing_2015_2024.csv')
df_walmart= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/Walmart_US_Revenue_and_Marketing_2016_2025.csv')
df_walmart_cotsco = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/Walmart_Costco_US_Market_Share_2016_2024.csv')


# print the first 5 rows for each dataset
print(df_costco.head(5))
print(df_walmart.head(5))
print(df_walmart_cotsco.head(5))

# print info for all datasets
print(df_costco.info())
print(df_walmart.info())
print(df_walmart_cotsco.info())

   Year  Costco Revenue (in billions USD)  Marketing Spend (in billions USD)
0  2015                            84.351                              8.308
1  2016                            86.579                              8.801
2  2017                            93.889                              9.423
3  2018                           102.286                             10.025
4  2019                           111.751                             10.973
   Year  Walmart Revenue (in billions USD)  Marketing Spend (in billions USD)
0  2016                              298.4                               60.0
1  2017                              307.8                               64.5
2  2018                              318.5                               66.0
3  2019                              331.7                               67.0
4  2020                              341.0                               68.2
   Year  U.S. Retail Market Size (in trillions USD)  \
0  2016                                        4.83
1  2017                                        5.04
2  2018                                        5.25
3  2019                                        5.40
4  2020                                        5.56

   Walmart U.S. Revenue (in billions USD)  Walmart Market Share (%)  \
0                                   307.8                       6.4
1                                   318.5                       6.3
2                                   331.7                       6.3
3                                   341.0                       6.3
4                                   370.0                       6.7

   Costco U.S. Revenue (in billions USD)  Costco Market Share (%)
0                                   83.0                      1.7
1                                   90.0                      1.8
2                                  100.0                      1.9
3                                  108.0                      2.0
4                                  115.0                      2.1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year                               10 non-null     int64
 1   Costco Revenue (in billions USD)   10 non-null     float64
 2   Marketing Spend (in billions USD)  10 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 372.0 bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year                               10 non-null     int64
 1   Walmart Revenue (in billions USD)  10 non-null     float64
 2   Marketing Spend (in billions USD)  10 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 372.0 bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        9 non-null      int64
 1   U.S. Retail Market Size (in trillions USD)  9 non-null      float64
 2   Walmart U.S. Revenue (in billions USD)      9 non-null      float64
 3   Walmart Market Share (%)                    9 non-null      float64
 4   Costco U.S. Revenue (in billions USD)       9 non-null      float64
 5   Costco Market Share (%)                     9 non-null      float64
dtypes: float64(5), int64(1)
memory usage: 564.0 bytes
None

In [ ]:
# check null
print(df_costco.isna().sum())
print(df_walmart.isna().sum())
print(df_walmart_cotsco.isna().sum())

Year                                 0
Costco Revenue (in billions USD)     0
Marketing Spend (in billions USD)    0
dtype: int64
Year                                 0
Walmart Revenue (in billions USD)    0
Marketing Spend (in billions USD)    0
dtype: int64
Year                                          0
U.S. Retail Market Size (in trillions USD)    0
Walmart U.S. Revenue (in billions USD)        0
Walmart Market Share (%)                      0
Costco U.S. Revenue (in billions USD)         0
Costco Market Share (%)                       0
dtype: int64

In [ ]:
# check duplicated
print(df_costco.duplicated().sum())
print(df_walmart.duplicated().sum())
print(df_walmart_cotsco.duplicated().sum())

0
0
0

The datasets is clean and no null and duplicated value are found. The next step is to merge all three dataset using outer join to preserve the data in each datasets (Cotsco have data for 2015 while Walmart has data for 2025)

In [ ]:
# merging the three dataset into one using outer join
market_competitors = pd.merge(df_costco, df_walmart, on='Year', how='outer')
market_competitors = pd.merge(market_competitors, df_walmart_cotsco, on='Year', how='outer')

# checking the dataset
market_competitors.head(5)

,Year,Costco Revenue (in billions USD),Marketing Spend (in billions USD)_x,Walmart Revenue (in billions USD),Marketing Spend (in billions USD)_y,U.S. Retail Market Size (in trillions USD),Walmart U.S. Revenue (in billions USD),Walmart Market Share (%),Costco U.S. Revenue (in billions USD),Costco Market Share (%)
0,2015,84.351,8.308,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016,86.579,8.801,298.4,60.0,4.83,307.8,6.4,83.0,1.7
2,2017,93.889,9.423,307.8,64.5,5.04,318.5,6.3,90.0,1.8
3,2018,102.286,10.025,318.5,66.0,5.25,331.7,6.3,100.0,1.9
4,2019,111.751,10.973,331.7,67.0,5.40,341.0,6.3,108.0,2.0

## Merging the datasets into unified dataset in excel3
All the cleaned dataset is combined into one unified dataset in excel before used in PowerBI. First a dictionary for each sheet name with their rrespective dataframe is defined. Then, the output file is set. pd ExcelWriter is used to combine all the file into one excel file.

In [ ]:
!pip install xlsxwriter

Collecting xlsxwriter
  Downloading xlsxwriter-3.2.5-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.5-py3-none-any.whl (172 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.3/172.3 kB 6.0 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.5

In [ ]:

# Dictionary: sheet name → dataframe
dataframes = {
    'FBA US Location': df_usa,
    'FBA Canada Location': df_canada,
    'FBA Inventory Tool': df_inventory_tool,
    'Amazon Stocks': df_stocks,
    'Income Statement': transp_income_stmt,
    'Quarterly Income Statement': transp_quarter_income,
    'Balance Sheet': transp_balance_sheet,
    'Cash Flow': transp_cash_flow,
    'Competitors': market_competitors
}


# Output file
output_excel = 'clean_dataset_AA.xlsx'

# Write to Excel with multiple sheets
with pd.ExcelWriter(output_excel, engine='xlsxwriter') as writer:
    for sheet_name, df in dataframes.items():
        df.to_excel(writer, sheet_name=sheet_name[:31], index=False)